selected_features:
- CE_CT1_original_firstorder_10Percentile
- CE_CT1_original_firstorder_Energy
- CE_CT1_original_firstorder_TotalEnergy
- CE_CT1_original_glcm_Idn
- CE_CT1_original_gldm_DependenceNonUniformity
- CE_CT1_original_glrlm_GrayLevelNonUniformity
- CE_CT1_original_glrlm_RunLengthNonUniformity
- CE_CT1_original_glszm_LargeAreaHighGrayLevelEmphasis
- CE_CT1_original_ngtdm_Coarseness
- CE_CT1_original_shape_MeshVolume
- CE_CT1_original_shape_MinorAxisLength
- CE_FLAIR_original_gldm_GrayLevelNonUniformity
- CE_FLAIR_original_glrlm_GrayLevelNonUniformity
- CE_FLAIR_original_glszm_GrayLevelNonUniformity
- CE_FLAIR_original_ngtdm_Coarseness
- CE_FLAIR_original_shape_MeshVolume
- CE_FLAIR_original_shape_MinorAxisLength
- CE_T1_original_firstorder_Energy
- CE_T1_original_firstorder_TotalEnergy
- CE_T1_original_glcm_Idmn
- CE_T1_original_gldm_DependenceNonUniformity
- CE_T1_original_glszm_LargeAreaHighGrayLevelEmphasis
- CE_T1_original_shape_MeshVolume
- CE_T1_original_shape_MinorAxisLength
- CE_T2_original_firstorder_Energy
- CE_T2_original_firstorder_TotalEnergy
- CE_T2_original_gldm_DependenceNonUniformity
- CE_T2_original_glrlm_RunLengthNonUniformity
- CE_T2_original_glszm_LargeAreaHighGrayLevelEmphasis
- CE_T2_original_ngtdm_Coarseness
- CE_T2_original_shape_MeshVolume
- CE_T2_original_shape_MinorAxisLength
- NC_CT1_original_shape_Maximum2DDiameterSlice
- NC_FLAIR_original_glcm_MaximumProbability
- NC_FLAIR_original_glszm_LargeAreaEmphasis
- NC_FLAIR_original_glszm_LargeAreaHighGrayLevelEmphasis
- NC_FLAIR_original_glszm_ZoneVariance
- NC_FLAIR_original_shape_Maximum2DDiameterSlice
- NC_T1_original_shape_Maximum2DDiameterSlice
- NC_T2_original_shape_Maximum2DDiameterSlice
n_selected: 40
majority_vote_threshold: 3
n_folds: 5
